---
title: "1-5-2 - Synapse Assessment"
author: "Tom Naber"
date: "`r format(Sys.Date(), '%B %d, %Y')`"

knit: (function(input, ...) {
  move_script <- here::here("Scripts", "move_output.R");
  output_folder <- here::here("Output", "HTML");
  rmarkdown::render(input, params = "ask");
  source(move_script);
  move_output(input, output_folder)})

output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    highlight: tango
    self_contained: false
    fig_width: 10
    fig_height: 6
    code_folding: hide
editor_options:
  markdown:
    wrap: 80
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height = "100%",
                      out.width = "100%")

knitr::opts_knit$set(root.dir = here::here())

library(ggplot2)
library(here)
library(sameplot)
```

# Test plotting
```{r}
print(getOption("knitr.in.progress"))
print(knitr::is_html_output())

args <- knitr::opts_knit$get("rmarkdown.pandoc.args")
if (is.null(args)) args <- character()

# Pandoc has used either --self-contained (older) or --embed-resources + --standalone (newer)
is_self_contained <- any(args == "--self-contained") ||
  (any(args == "--embed-resources") && any(args == "--standalone"))
print(is_self_contained)
```

```{r}
p <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) + ggplot2::geom_point()
sameplot(p, file = "plot.png", save = TRUE)
p
```


